### ISSUE TITLE
[Tracking issue]: Steps to improve safety on Android 10 and below for those using External storage

### ISSUE THREAD

**Issue by nain-F49FF806** [nain-F49FF806/anemo-aer#10]
### Describe what you'd like to see added to the app

In regards to #8

Steps:
- [x] Add a warning in the next release
  - [x] When using external storage on Android10 (and below), there should be infowarning in Aer storage
  - [ ] <del>In storage settings page, user may be discouraged to use External storage if on Android 10 (and below)</del>
- [x] Change the defaults for Android 10 (and below) to use safer internal storage
- [x] Add summarized documentation re Android storage privacy that can be useful to everyone. (see [wiki page])

[wiki page]: https://github.com/nain-F49FF806/anemo-aer/wiki/Android-storage-privacy-story "Android storage privacy story"

**Comment by nain-F49FF806** [comment]
resolves #8
